# Streamlit Cloud Secrets Configuration
# This file should be configured in your Streamlit Cloud dashboard

[general]
# Add any API keys or sensitive configuration here
# Example:
# api_key = "your_api_key_here"

[database]
# Add database connections if needed
# Example:
# host = "your_database_host"
# port = 5432
# username = "your_username"
# password = "your_password"

[aws]
# Add AWS credentials if using S3 or other AWS services
# Example:
# access_key_id = "your_access_key"
# secret_access_key = "your_secret_key"
# region = "us-east-1"
